name: blind_assistant
description: A Flutter application to assist visually impaired users.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  speech_to_text: ^7.0.0
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  http: ^1.2.0
  flutter_tts: ^3.8.5
  permission_handler: ^11.3.0
  just_audio: ^0.9.36

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true 